// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import LoginUserReducer from "../login_user_reducer";
import RegisterUserReducer from "../register_user_reducer";

export type LoginUserParams = __Infer<typeof LoginUserReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;

